version: "3.8"
services:
  multichain_vue:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: multichain_vue:v0.1
    entrypoint: .docker/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - '.:/usr/src/nuxt-app'
    networks:
      - multichain_vue

networks:
  multichain_vue:
    driver: bridge